### ISSUE TITLE
Problem with Telnetupload

### ISSUE THREAD

**Issue by Tilman** [ArchimedesPi/esp8266-luaupload#9]
Can not upload scripts via Telnet.

As you can see my Telnetserver is working, but the upload script can't connect.

```
Tilmans-MacBook-Pro:esp8266-luaupload Tilman$ telnet 192.168.1.7 2323
Trying 192.168.1.7...
Connected to 192.168.1.7.
Escape character is '^]'.
Welcome to NodeMcu world.
^]
telnet> close
Connection closed.
```

```
Tilmans-MacBook-Pro:esp8266-luaupload Tilman$ sudo python luaupload.py telnetupload init.lua -u 192.168.1.7:2323
Could not connect to 192.168.1.7:2323
Traceback (most recent call last):
  File "luaupload.py", line 89, in <module>
    cli()
  File "/Library/Python/2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "luaupload.py", line 53, in telnetupload
    esp.upload(f.read(), {'filename': filename})
  File "/Users/Tilman/Documents/Programme/Python/esp8266-luaupload/luaupload/esp8266.py", line 41, in upload
    self.send('file.remove("{file}")\r\n'.format(file=espoptions['filename']))
  File "/Users/Tilman/Documents/Programme/Python/esp8266-luaupload/luaupload/esp8266.py", line 36, in send
    self.connection.send(data)
socket.error: [Errno 57] Socket is not connected
```

Can you please help me out, to fix this.
Thanks Til

**Comment by ArchimedesPi** [comment]
Sorry - I have a backlog of *so many other things* right now - this is just
a side project, and I'm a student. I know how it feels to not get answers
about a bug report, so I'm *really* sorry :(
I'm going to try to figure this out - I should get back to you in a week or
so.

**Comment by raz123** [comment]
Bump! Same issue :) :+1:
